config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :skills, only: [:index]
  resources :articles, only: [:index]

  get 'about_me/index'

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.where(active: true)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all.where(active: true)
	end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	def index
		@skills = Skill.all.where(active: true)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/about_me/index.html.erb
<div class="container">
  <div class="row">
    <h3>WORK EXPERIENCE</h3>
    <div class="col-md">
      <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
        <div class="card-body">
          <h5 class="card-title">Full Stack Web Developer</h5>
          <p class="card-text">
            <strong>ThinkWide-PGO</strong><br>
            02/2023 - Present, Hyderabad<br><br>

            - 1+ years experince on ruby on rails, developed and implemented user-friendly, responsive web applications using HTML, CSS, and JavaScript while following Ruby on Rails framework convention.<br><br>

            - Collaborated with the design team to create visually appealing and intuitive user interfaces, ensuring seamless user experiences within the Ruby on Rails environment.<br><br>

            - Conducted thorough testing and debugging across multiple browsers and devices to ensure cross-platform compatibility, consistent functionality, and a smooth experience with Ruby on Rails.<br><br>

            - Implemented Redis for creating background jobs, placing those jobs on multiple queues, and processing them later.<br><br>

            - Maintained and updated existing web applications, addressing bugs, implementing enhancements, and improving overall code quality within the Ruby on Rails framework.<br><br>

            - Worked closely with back-end developers and stakeholders to seamlessly integrate front-end components with server-side logic, APIs, and databases within the Ruby on Rails context.<br><br>

            - Documented code, processes, and project updates meticulously to establish a comprehensive and accessible knowledge base for the team and future developers working with Ruby on Rails.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>🚀 Hey there, I'm Nitin Kumar!</h1>
      <p>With a strong foundation in both React and Ruby on Rails, I am a dedicated full-stack developer committed to delivering high-quality, scalable solutions.</p>
      <p>This page showcases my skills and projects done on react and ruby on rails.</p>
    </div>

    <div class="col-md-6">
      <img src="<%= asset_path('react_logo.jpeg') %>" style="width: 150px" alt="React Logo" class="technical-image">
      <img src="<%= asset_path('rails_logo.png') %>" style="width: 140px;" alt="Ruby on Rails Logo" class="technical-image">
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
		<h3>Articles</h3>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">Currency Converter</h5>	
            <p class="card-text">This currency converter gives live data convertion of currency. This has been by using API for information. This page also has a button called historic chart which gives you graph of how the prices has changed over the time. Used chartkick for shoing graphs.</p>
            	<a href="https://github.com/Nitin181901/currency_converter" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">Details for Ruby on rails internship</h5>  
            <p class="card-text">Completed 3 months paid intership working on ruby on rails.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">Weather-app using React</h5>  
            <p class="card-text">This is a weather app, you can search and city or country and you will get the data about the city. Used API for data of live weather when searched. Handled error when location is not found. Gave beautiful css for it.</p>
              <a href="https://github.com/Nitin181901/weather-app" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">TIC-TAC-TOE game using React</h5>  
            <p class="card-text">Developed a game using react, gave backend code to show winner, we can also time travel to moves in past, gave beautful css for the game.</p>
              <a href="https://github.com/Nitin181901/tic-tac-toe" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
  <style>
    /* Custom styles to override Bootstrap styles */
    @media (max-width: 767px) {
      nav.navbar .navbar-collapse {
        display: flex !important; /* Override the default display: none; for mobile */
        flex-direction: column; /* Stack items vertically */
      }

      nav.navbar .navbar-nav {
        width: 100%;
        text-align: left; /* Align the links to the left */
      }

      nav.navbar .navbar-nav .nav-item {
        width: 100%;
      }

      .navbar-nav-side-by-side {
        display: flex;
        flex-direction: row;
        justify-content: space-between;
      }
    }

    nav.navbar {
      background-color: #333 !important; 
      --bs-navbar-padding-x: 0;
      --bs-navbar-padding-y: 0rem;
    }

    nav.navbar .navbar-brand,
    nav.navbar .navbar-nav .nav-link,
    nav.navbar .navbar-text {
      color: #fff !important;
    }
  </style>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= articles_path %>">Nitin's Portfolio</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-nav-side-by-side">
          <li class="nav-item">
            <a class="nav-link" href="<%= about_me_index_path %>">Past-Work</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= skills_path %>">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= projects_path %>">Projects</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <style>
      body {
        background-color: #000;
        color: #fff;
      }

      .container {
        margin-top: 20px;
      }

      .technical-image {
        width: 100%;
        height: auto;
        margin-bottom: 20px;
      }
    </style>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <h3>My Projects</h3>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">Currency Converter</h5>  
            <p class="card-text">This currency converter gives live data convertion of currency. This has been by using API for information. This page also has a button called historic chart which gives you graph of how the prices has changed over the time. Used chartkick for shoing graphs.</p>
              <a href="https://github.com/Nitin181901/currency_converter" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">Weather-app using React</h5>  
            <p class="card-text">This is a weather app, you can search and city or country and you will get the data about the city. Used API for data of live weather when searched. Handled error when location is not found. Gave beautiful css for it.</p>
              <a href="https://github.com/Nitin181901/weather-app" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <h5 class="card-title">TIC-TAC-TOE game using React</h5>  
            <p class="card-text">Developed a game using react, gave backend code to show winner, we can also time travel to moves in past, gave beautful css for the game.</p>
              <a href="https://github.com/Nitin181901/tic-tac-toe" class="btn btn-light">GitHub link</a>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/skills/index.html.erb
<div class="container">
  <div class="row">
    <h3>My Skills</h3>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">Ruby on Rails</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">Ruby on Rails</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">React</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(80%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">MySql</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(80%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">Git</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">HTML</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">CSS</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">Javascript</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(90%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">AJAX</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(90%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">API integration</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card" style="background-color: #333; color: #fff; margin-bottom: 20px;">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <h5 class="card-title">Postman</h5>
                <%# proficiency = skill.proficiency.to_i %>
              </div>
              <div class="col-6">
                <h6 class="card-title">Proficiency(100%)</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>